apiVersion: v1
kind: ServiceAccount
metadata:
  name: odoo-operator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-operator
  labels:
    app: odoo-operator
spec:
  replicas: 1 # make sure to not have more than one replicas
  strategy:
    type: Recreate # make sure the old pod is being killed before the new pod is being created
  selector:
    matchLabels:
      app: odoo-operator
  template:
    metadata:
      labels:
        app: odoo-operator
    spec:
      serviceAccountName: odoo-operator
      containers:
      - name: odoo-operator
        image: odoo-operator:v5.0
        imagePullPolicy: IfNotPresent
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: odoo-operator
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
- apiGroups: ["operators.nurlanf.github.io"]
  resources: ["odoos"]
  verbs: ["*"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: odoo-operator
subjects:
- kind: ServiceAccount
  name: odoo-operator
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: odoo-operator
  apiGroup: rbac.authorization.k8s.io
